apiVersion: v1
kind: Service
metadata:
  name: {{ include "yb-iot-helm.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "yb-iot-helm.name" . }}
    helm.sh/chart: {{ include "yb-iot-helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: "ui"
  selector:
    app.kubernetes.io/name: {{ include "yb-iot-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
